global:
  scrape_interval: 5s # Intervalo de coleta

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
  
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'livros-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['livros-service:8081']

# TODO: adicionar mais jobs para os outros serviços
# TODO: parei aqui