spring:
  application:
    name: bibliotech-backend

# configurações do flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

# configurações do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
