spring:
  application:
    name: bibliotech-backend

  # configurações do flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

# configurações do banco de dados (oculto)
  config:
    import: ./application-secret.yml
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

# configurações do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

server:
  port: 8888

