spring:
  application:
    name: bibliotech-backend

  # configurações do flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

# configurações do banco de dados (oculto)
  config:
    import: ./application-secret.yml

# configurações do JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# configurações do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888

